<a href="https://colab.research.google.com/github/Nfsu26/utkarshraj/blob/main/NLP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
Sentence = 'Today is 04th March, 2024 and Monday. We are currently at NFSU'
token_sentence = str.split(Sentence)
print(token_sentence)


['Today', 'is', '04th', 'March,', '2024', 'and', 'Monday.', 'We', 'are', 'currently', 'at', 'NFSU']


In [ ]:
vocab = sorted(set(token_sentence))
print(vocab)


['04th', '2024', 'March,', 'Monday.', 'NFSU', 'Today', 'We', 'and', 'are', 'at', 'currently', 'is']


In [ ]:
num_tokens = len(token_sentence)
vocab_size = len(vocab)
onehot_vectors = np.zeros((num_tokens, vocab_size), int)


In [ ]:
for i, word in enumerate(token_sentence):
  onehot_vectors[i,vocab.index(word)] =1
print(onehot_vectors)
print(pd.DataFrame (onehot_vectors, columns= vocab))


[[0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]]
    04th  2024  March,  Monday.  NFSU  Today  We  and  are  at  currently  is
0      0     0       0        0     0      1   0    0    0   0          0   0
1      0     0       0        0     0      0   0    0    0   0          0   1
2      1     0       0        0     0      0   0    0    0   0          0   0
3      0     0       1        0     0      0   0    0    0   0          0   0
4      0     1       0        0     0      0   0    0    0   0          0   0
5      0     0       0        0     0      0   0    1    0   0          0   0
6      0     0       0        1     0      0   0    0    0   0          0   0
7      0     0       0        0     0      0   1   